name: .NET CI

# Trigger the workflow on push or pull request to the main branch
on:
  push

# Define the job to run
jobs:
  build:

    # The operating system the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK (specify the .NET version)
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.5.2'  # Specify the .NET version (use the version your project requires)

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=javaprojectreachability12345
            -Dsonar.projectKey=javaprojectreachability12345_dotnetnew